apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cts-mtls
  namespace: rob
spec:
  secretName: cts-mtls
  secretTemplate:
    annotations:
      my-secret-annotation: "cert-manager-generated"
  duration: 21600h # 900 days.
  literalSubject: "UID=openam_cts,OU=admins,OU=famrecords,OU=openam-session,OU=tokens"
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
    - client auth
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  # Issuer references are always required.
  dnsNames:
    - "*.ds"
    - "*.ds-idrepo"
    - "*.ds-cts"
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
  keystores:
  #  jks:
  #    create: true
  #    passwordSecretRef: # Password used to encrypt the keystore
  #      key: pass
  #      name: keystores
    jks:
      create: true
      passwordSecretRef:
        name: am-passwords
        key: .storepass
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: config-mtls
spec:
  secretName: config-mtls
  secretTemplate:
    annotations:
      my-secret-annotation: "cert-manager-generated"
  duration: 21600h # 900 days.
  literalSubject: "UID=am-config,OU=admins,OU=am-config"
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
    - client auth
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  # Issuer references are always required.
  dnsNames:
    - "*.ds"
    - "*.ds-idrepo"
    - "*.ds-cts"
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
  keystores:
  #  jks:
  #    create: true
  #    passwordSecretRef: # Password used to encrypt the keystore
  #      key: pass
  #      name: keystores
    jks:
      create: true
      passwordSecretRef:
        name: am-passwords
        key: .storepass
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-mtls
spec:
  secretName: identity-mtls
  secretTemplate:
    annotations:
      my-secret-annotation: "cert-manager-generated"
  duration: 21600h # 900 days.
  literalSubject: "UID=am-identity-bind-account,OU=admins,OU=identities"
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
    - client auth
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  # Issuer references are always required.
  dnsNames:
    - "*.ds"
    - "*.ds-idrepo"
    - "*.ds-cts"
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
  keystores:
  #  jks:
  #    create: true
  #    passwordSecretRef: # Password used to encrypt the keystore
  #      key: pass
  #      name: keystores
    jks:
      create: true
      passwordSecretRef:
        name: am-passwords
        key: .storepass