apiVersion: v1
kind: Service
metadata:
  name: idm
spec:
  ports:
  - name: idm
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: idm-https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: idm
  type: ClusterIP
